:output:
  Thing: &thing
    :options:
      :fields:
        - id
        - name
        - parent_id
        - marked
        - lft
        - rgt
        - tree_depth
        - created
        - updated
