:output:
  Thing: &thing
    :options:
      :fields:
        - id
        - name
        - parent_id
        - marked
        - lft
        - rgt
        - tree_depth
        - created
        - updated
  Audit: &audit
    :options:
      :fields:
        - id
        - a_id
        - a_type
        - asc_id
        - asc_type
        - user
        - action
        - changes
        - v
        - created
