# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 26dba110fdc07affedc261076cd485da22dee1718833ee9ff185daa1ccf35ae4bf2526575ff22a7de6198c90a1f38aa4a7bd7d092b64465fb418fa39ae37297d

test:
  secret_key_base: a08c57dc8ed4b1a030bf4beb5ff6be0fb651feb6067e3cc4756e7d5ed9aa3d1dce3942bbec9b00ad69b188ca9b6bdffd686ae86b222b288baa4f1f2138f88d09

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
